# Sourcery configuration for REPO-Magic
python:
  version: "3.9"
  rules:
    - name: "avoid-magic-numbers"
    - name: "avoid-redundant-if"
    - name: "avoid-single-character-names"
    - name: "avoid-unnecessary-else"
    - name: "avoid-unused-variables"
    - name: "consider-using-f-string"
    - name: "consider-using-join"
    - name: "consider-using-ternary"
    - name: "duplicate-code"
    - name: "empty-docstring"
    - name: "function-too-complex"
    - name: "line-too-long"
    - name: "missing-docstring"
    - name: "no-else-return"
    - name: "no-self-use"
    - name: "simplifiable-if-statement"
    - name: "too-few-public-methods"
    - name: "too-many-arguments"
    - name: "too-many-branches"
    - name: "too-many-locals"
    - name: "too-many-return-statements"
    - name: "unnecessary-comprehension"
    - name: "unnecessary-lambda"
    - name: "unused-import"
    - name: "unused-variable"
    - name: "use-dict-literal"
    - name: "use-list-literal"
    - name: "use-set-literal"
    - name: "use-sys-exit"

bash:
  rules:
    - name: "avoid-global-variables"
    - name: "avoid-hardcoded-paths"
    - name: "avoid-long-functions"
    - name: "avoid-magic-numbers"
    - name: "avoid-nested-loops"
    - name: "avoid-redundant-echo"
    - name: "avoid-unnecessary-else"
    - name: "consider-using-printf"
    - name: "duplicate-code"
    - name: "empty-function"
    - name: "function-too-complex"
    - name: "line-too-long"
    - name: "missing-error-handling"
    - name: "missing-input-validation"
    - name: "no-else-return"
    - name: "simplifiable-if-statement"
    - name: "too-many-arguments"
    - name: "too-many-branches"
    - name: "too-many-locals"
    - name: "unnecessary-echo"
    - name: "unused-variable"
    - name: "use-quotes-for-strings"
    - name: "use-strict-mode"

exclude:
  - "*.log"
  - "*.tmp"
  - "*.backup"
  - "docs/"
  - ".git/"

include:
  - "*.sh"
  - "*.py"
  - "*.yaml"
  - "*.yml"
