name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create release
      run: |
        echo "Creating release for tag: $GITHUB_REF"
        
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        echo "Version: $VERSION"
        
        # Create release notes
        cat > release_notes.md << EOL
        # Release $VERSION
        
        ## Changes
        - Automated release from CI/CD pipeline
        - All tests passed
        - Ready for production deployment
        
        ## Installation
        \`\`\`bash
        # Download and run installer
        curl -fsSL https://raw.githubusercontent.com/grimm00/REPO-Magic/main/modinstaller.sh | bash
        \`\`\`
        EOL
        
        # Create GitHub release
        gh release create "$VERSION" \
          --title "Release $VERSION" \
          --notes-file release_notes.md \
          --latest
          
    - name: Update documentation
      run: |
        echo "Updating documentation for release $VERSION"
        # This would typically update version numbers in docs
